name: yt-summarizer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - ffmpeg
  - jpeg
  - pip:
    - yt-dlp>=2023.12.30
    - openai-whisper>=20231117
    - transformers>=4.36.0
    - pytube>=15.0.0
    - accelerate>=0.26.0
    - sentencepiece
    - protobuf>=3.20.0
    - gradio>=4.0.0 